# Generated by Django 4.0.4 on 2022-05-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0004_notebook_note_notebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='titulo',
            field=models.CharField(default='Nuevo Libro de Notas', max_length=250, unique=True),
        ),
    ]
